// <auto-generated />
using System;
using AerolineaV1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AerolineaV1.Migrations.Vuelo
{
    [DbContext(typeof(VueloContext))]
    [Migration("20200304030645_ThirdCreate")]
    partial class ThirdCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AerolineaV1.Models.Vuelo", b =>
                {
                    b.Property<int>("VueloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("FechaAbordaje")
                        .HasColumnType("DateTime");

                    b.Property<string>("ModeloAvion")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Pasajeros")
                        .HasColumnType("int");

                    b.Property<string>("Piloto")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("VueloID");

                    b.ToTable("Vuelos");
                });
#pragma warning restore 612, 618
        }
    }
}
